import "./css/style.css";

import { Inter } from "next/font/google";
import Theme from "./theme-provider";
import Header from "@/components/ui/header";
import Footer from "@/components/ui/footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* keep body free of fixed light colors */}
      <body className={`${inter.variable} font-inter tracking-tight antialiased`}>
        <Theme>
          {/* site-wide light/dark surface + text */}
          <div className="min-h-dvh flex flex-col overflow-hidden supports-[overflow:clip]:overflow-clip bg-white text-slate-900 dark:bg-slate-950 dark:text-slate-100">
            <Header />
            <main className="grow">{children}</main>
            <Footer border={true} />
          </div>
        </Theme>
      </body>
    </html>
  );
}